Fix r41275 unused TOLERANCE
ogrlineref.cpp:52:18: error: unused variable 'TOLERANCE' [-Werror,-Wunused-const-variable]
constexpr double TOLERANCE = 0.00008983153;


git-svn-id: https://svn.osgeo.org/gdal/trunk@41277 f0d54148-0727-0410-94bb-9a71ac55c965