gdaldataset.cpp: Address GCC 8 warning
Although it seems impossible that `poBand = GetRasterBand(iBand + 1);`
is NULL, I could not affirm the same for
`poBand = GetRasterBand(panBandMap[iBand]);`

gdaldataset.cpp: In member function ‘virtual CPLErr GDALDataset::AdviseRead(int, int, int, int, int, int, GDALDataType, int, int*, char**)’
gdaldataset.cpp:2781:68: error: potential null pointer dereference [-Werror=null-dereference]
                                   nBufYSize, eBufType, papszOptions);