Add missing CPL_TO_BOOL for bComplex in GDALDataTypeUnion().
/home/travis/build/rouault/gdal_coverage/gdal/port/cpl_port.h:905:9: error: ‘MSVCPedanticBool::MSVCPedanticBool(int)’ is private
gdal_misc.cpp:69:69: error: within this context


git-svn-id: https://svn.osgeo.org/gdal/trunk@34032 f0d54148-0727-0410-94bb-9a71ac55c965