Add missing <cstdint headers for uint*_t types
Without the change buld fails on upcomig `gcc-13` as:

    frmts/mrf/LERCV1/Lerc1Image.cpp: In member function 'bool Lerc1NS::Lerc1Image::isallsameval(int, int, int, int) const':
    frmts/mrf/LERCV1/Lerc1Image.cpp:730:5: error: 'uint32_t' was not declared in this scope
      730 |     uint32_t val = *reinterpret_cast<const uint32_t *>(&(*this)(r0, c0));
          |     ^~~~~~~~
    /build/gdal/frmts/mrf/LERCV1/Lerc1Image.cpp:29:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
       28 | #include <algorithm>
      +++ |+#include <cstdint>