CMake: add/fix CSharp support
Note that it is currently disabled on the CMake Windows CI because we
get the following error:
```
Microsoft (R) Visual C# 2005 Compiler version 8.00.50727.9031
for Microsoft (R) Windows (R) 2005 Framework version 2.0.50727
Copyright (C) Microsoft Corporation 2001-2005. All rights reserved.
d:\a\gdal\gdal\swig\csharp\AssemblyInfo.cs(98,12): error CS0246: The type or namespace name 'SecurityRules' could not be found (are you missing a using directive or an assembly reference?) [D:\a\gdal\gdal\build\swig\csharp\csharp_samples.vcxproj]
```

Things works fine locally for me with Microsoft (R) Visual C# Compiler version 3.9.0-6.21124.20 (db94f4cc)