shapelib: update from upstream: general cleanup; no functional changes (#3502)
* shapelib: update from upstream.

Upstream at 3e59b35009f81538c2f3014a20c7abfc7a964ba3

General cleanup.  No functional changes.

- Use stdbool true/false for internal variables
- Localize variables
- Combine variable definition and initialization when possible
- Add const when possible
- Remove or comment out most unused variables
- Remove some extra empty space
- Add some missing headers
- Sort standard headers
- Move static variable to after includes
- Remove RCS/CVS/SVN Id/Revision tags except for SHP_CVSID

* shpopen.c: Remove goto from SHPCreateLL and directly handle cleanup

https://github.com/OSGeo/shapelib/commit/2025ce22196f100a773e2d0bbdc86cfd2ad0ad18

There was a "used uninitialized" from localizing variables:

    ./shpopen.c:973:9: error: variable 'fpSHX' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
        if( fpSHP == SHPLIB_NULLPTR )