Revert "GML: relax identification checks when papszAllowedDrivers[] contains only the driver name"
This reverts commit 36b7a5cc64f9853c46200d906c37f7c91a25e3f7.

To avoid test failure on osx

45: =================================== FAILURES ===================================
45: _____________________ test_gml_read_compound_crs_lat_long ______________________
45:
45: tmp_path = PosixPath('/private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/pytest-of-runner/pytest-2/test_gml_read_compound_crs_lat0')
45:
45:     def test_gml_read_compound_crs_lat_long(tmp_path):
45:
45:         shutil.copy("data/gml/citygml_compound_crs.gml", tmp_path)
45:
45:         # open CityGML file
45:         gml = ogr.Open(tmp_path / "citygml_compound_crs.gml")
45:
45:         # check number of layers
45: >       assert gml.GetLayerCount() == 1, "Wrong layer count"
45: E       AttributeError: 'NoneType' object has no attribute 'GetLayerCount'
45:
/Users/runner/work/gdal/gdal/build/autotest/ogr/ogr_gml.py:639: AttributeError