Fix incorrect initialization of vrColumn introduced in r35151.
In member function ‘virtual int VFKDataBlockSQLite::LoadGeometryPolygon()’:
vfkdatablocksqlite.cpp:468:44: error: zero as null pointer constant [-Werror=zero-as-null-pointer-constant]


git-svn-id: https://svn.osgeo.org/gdal/trunk@35152 f0d54148-0727-0410-94bb-9a71ac55c965