CI: build_mac: fix issue with libkml
Recent builds fails with
```
/usr/local/Cellar/libkml/1.3.0_1/include/kml/base/xml_element.h:31:10: fatal error: 'boost/intrusive_ptr.hpp' file not found
```

This is due to this change in the libkml recipee
https://github.com/Homebrew/homebrew-core/pull/128140
which makes boost a build-only dependency.
Explicit installation of boost is now needed to use libkml headers