CMake: enable gdal_priv.h precompiled header if CMake USE_PRECOMPILED_HEADERS=ON
Can speed up cold builds by 30%

It is a bit experimental for now, so it isn't enabled by default, because:
- it currently causes linking issues with MSVC
- CLang Static Analyzer analysis has false positives with it
- Strange issue seen in the android CI configuration with a
  fatal error: file '/home/runner/work/gdal/gdal/build_android_cmake/CMakeFiles/gdal_priv_header.dir/cmake_pch.h' has been modified since the precompiled header '/home/runner/work/gdal/gdal/build_android_cmake/CMakeFiles/gdal_priv_header.dir/cmake_pch.h.pch' was built: mtime changed (https://github.com/rouault/gdal/actions/runs/12113235664/job/33767887119)