int bNeedSecondPass -> bool bNeedSecondPass in ogrtopojsonreader.
Converting static function ParseObjectMain from int to bool caused in MS VC:
- error C2220: warning treated as error - no 'object' file generated 
- warning C4805: '|=': unsafe mix of type 'int' and type 'bool' in operation 
 


git-svn-id: https://svn.osgeo.org/gdal/trunk@32463 f0d54148-0727-0410-94bb-9a71ac55c965