gdal2tiles: fix issue with multiprocessing and the gdal2tiles launcher script on Windows and Python >= 3.8 (fixes #4951)
Fixes the following exception:
```
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python39\Scripts\gdal2tiles.py", line 4, in <module>
    __import__('pkg_resources').run_script('GDAL==3.4.0', 'gdal2tiles.py')
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\pkg_resources\__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\pkg_resources\__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "c:\osgeo4w\apps\python39\lib\site-packages\gdal-3.4.0-py3.9-win-amd64.egg\EGG-INFO\scripts\gdal2tiles.py", line 11, in <module>
    sys.exit(main(sys.argv))
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\GDAL-3.4.0-py3.9-win-amd64.egg\osgeo_utils\gdal2tiles.py", line 3257, in main
    multi_threaded_tiling(input_file, output_folder, options)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\GDAL-3.4.0-py3.9-win-amd64.egg\osgeo_utils\gdal2tiles.py", line 3206, in multi_threaded_tiling
    pool = Pool(processes=nb_processes)
  File "C:\OSGeo4W\apps\Python39\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\OSGeo4W\apps\Python39\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\OSGeo4W\apps\Python39\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\OSGeo4W\apps\Python39\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\OSGeo4W\apps\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\OSGeo4W\apps\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\OSGeo4W\apps\Python39\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\OSGeo4W\apps\Python39\lib\multiprocessing\spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
```

Running directly the osgeo_utils\gdal2tiles.py script was a potential
workaround too.