Remove unused bUpdateAccess member of OGRGeomediaTableLayer.
bUpdateAccess was added with the initial commit of r21545 but never use.

Moving bUpdateAccess to the ctor initializer list found the unused member in:

https://travis-ci.org/rouault/gdal_coverage/builds/154049790 - trunk_trusty

In file included from ogrgeomediatablelayer.cpp:31:
./ogr_geomedia.h:96:25: error: private field 'bUpdateAccess' is not used
      [-Werror,-Wunused-private-field]

git-svn-id: https://svn.osgeo.org/gdal/trunk@35177 f0d54148-0727-0410-94bb-9a71ac55c965