Avoid perl binding failures due to isnan clash
examples look like:

C:\berrybrew\5.26.1_64_PDL\perl\lib\CORE/win32.h:361:16: error: '_isnan' is not a member of 'std'
 #define isnan  _isnan /* ...same libraries as MSVC */
                ^
C:/shawn/git/perl-alien-gdal/blib/lib/auto/share/dist/Alien-gdal/include/cpl_port.h:661:51: note: in expansion of macro 'isnan'
 static inline int CPLIsNan(float f) { return std::isnan(f); }
                                                   ^
                ^