Summary: Attempt to fix compilation error for mingw in mitab_mapfile.cpp.
Probably introduced by r35603.

mitab_mapfile.cpp: In member function ‘int TABMAPFile::Open(const char*, TABAccess, GBool, int)’:
mitab_mapfile.cpp:512: error: aggregate ‘VSIStatBufL sStatBuf’ has incomplete type and cannot be defined


git-svn-id: https://svn.osgeo.org/gdal/trunk@35606 f0d54148-0727-0410-94bb-9a71ac55c965