Force size to int to fix casting issue with size in marfa_dataset.cpp.
Caused by r36271.

marfa_dataset.cpp:1866:29: error: comparison of integers of different signs: 'GUIntBig' (aka 'unsigned long long') and 'int' [-Werror,-Wsign-compare]


git-svn-id: https://svn.osgeo.org/gdal/trunk@36274 f0d54148-0727-0410-94bb-9a71ac55c965